/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     WIDTH = WIDTH
*/
module adder_41 (
    input select,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] sum,
    output reg z,
    output reg v,
    output reg n
  );
  
  localparam WIDTH = 5'h10;
  
  
  reg [15:0] sumI;
  
  reg [15:0] xb;
  
  always @* begin
    if (select) begin
      xb = -b;
    end else begin
      xb = b;
    end
    sumI = a + xb;
    v = (a[15+0-:1] & xb[15+0-:1] & ~sumI[15+0-:1]) | (~a[15+0-:1] & ~xb[15+0-:1] & sumI[15+0-:1]);
    if (sumI == 16'h0000) begin
      z = 1'h1;
    end else begin
      z = 1'h0;
    end
    n = sumI[15+0-:1];
    sum = sumI;
  end
endmodule
