/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     WIDTH = WIDTH
*/
module boolean_44 (
    input select0,
    input select1,
    input select2,
    input select3,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] result
  );
  
  localparam WIDTH = 5'h10;
  
  
  integer i;
  
  always @* begin
    for (i = 1'h0; i < 5'h10; i = i + 1) begin
      if (b[(i)*1+0-:1]) begin
        if (a[(i)*1+0-:1]) begin
          result[(i)*1+0-:1] = select3;
        end else begin
          result[(i)*1+0-:1] = select2;
        end
      end else begin
        if (a[(i)*1+0-:1]) begin
          result[(i)*1+0-:1] = select1;
        end else begin
          result[(i)*1+0-:1] = select0;
        end
      end
    end
  end
endmodule
