/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     WIDTH = WIDTH
*/
module multiplier_37 (
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] product
  );
  
  localparam WIDTH = 5'h10;
  
  
  always @* begin
    product = a * b;
  end
endmodule
