/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module randomSet_17 (
    input clk,
    input next,
    input rst,
    output reg [63:0] out
  );
  
  
  
  wire [32-1:0] M_random1_num;
  pn_gen_39 random1 (
    .clk(clk),
    .next(next),
    .rst(rst),
    .seed(32'h00000000),
    .num(M_random1_num)
  );
  wire [32-1:0] M_random2_num;
  pn_gen_39 random2 (
    .clk(clk),
    .next(next),
    .rst(rst),
    .seed(32'h00000001),
    .num(M_random2_num)
  );
  
  reg [63:0] outI;
  
  integer i;
  
  always @* begin
    outI[0+3-:4] = M_random1_num[0+3-:4];
    outI[4+3-:4] = M_random1_num[4+3-:4];
    outI[8+3-:4] = M_random1_num[8+3-:4];
    outI[12+3-:4] = M_random1_num[12+3-:4];
    outI[16+3-:4] = M_random1_num[16+3-:4];
    outI[20+3-:4] = M_random1_num[20+3-:4];
    outI[24+3-:4] = M_random1_num[24+3-:4];
    outI[28+3-:4] = M_random1_num[28+3-:4];
    outI[32+3-:4] = M_random2_num[0+3-:4];
    outI[36+3-:4] = M_random2_num[4+3-:4];
    outI[40+3-:4] = M_random2_num[8+3-:4];
    outI[44+3-:4] = M_random2_num[12+3-:4];
    outI[48+3-:4] = M_random2_num[16+3-:4];
    outI[52+3-:4] = M_random2_num[20+3-:4];
    outI[56+3-:4] = M_random2_num[24+3-:4];
    outI[60+3-:4] = M_random2_num[28+3-:4];
    for (i = 1'h0; i < 5'h10; i = i + 1) begin
      if (outI[(i)*4+3-:4] == 1'h0) begin
        out[(i)*4+3-:4] = 4'hf;
      end else begin
        out[(i)*4+3-:4] = outI[(i)*4+3-:4];
      end
    end
  end
endmodule
