/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module debounce_2 (
    input clk,
    input in,
    output reg out
  );
  
  
  
  reg dynamicRst;
  
  wire [8-1:0] M_hold_value;
  counter_21 hold (
    .clk(clk),
    .rst(dynamicRst),
    .value(M_hold_value)
  );
  
  reg M_state_d, M_state_q = 1'h0;
  
  always @* begin
    M_state_d = M_state_q;
    
    dynamicRst = 1'h0;
    if (in) begin
      dynamicRst = 1'h1;
      M_state_d = 1'h1;
    end else begin
      if (M_hold_value) begin
        M_state_d = 1'h0;
      end
    end
    if (M_state_q) begin
      out = 1'h1;
    end else begin
      out = 1'h0;
    end
  end
  
  always @(posedge clk) begin
    M_state_q <= M_state_d;
  end
  
endmodule
