/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     WIDTH = 2
*/
module decoder2_18 (
    input [1:0] we_adr,
    input inp,
    output reg o0,
    output reg o1,
    output reg o2
  );
  
  localparam WIDTH = 2'h2;
  
  
  always @* begin
    if (we_adr[0+0-:1] == 1'h1) begin
      if (we_adr[1+0-:1]) begin
        o0 = 1'h0;
        o1 = 1'h0;
        o2 = 1'h0;
      end else begin
        o0 = 1'h0;
        o1 = inp;
        o2 = 1'h0;
      end
    end else begin
      if (we_adr[1+0-:1]) begin
        o0 = 1'h0;
        o1 = 1'h0;
        o2 = inp;
      end else begin
        o0 = inp;
        o1 = 1'h0;
        o2 = 1'h0;
      end
    end
  end
endmodule
