/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module dig2to1_19 (
    input [7:0] num,
    output reg [7:0] out
  );
  
  
  
  always @* begin
    if (num < 4'ha) begin
      out = {4'h0, num[0+3-:4]};
    end else begin
      
      case (num)
        4'ha: begin
          out = 8'h10;
        end
        4'hb: begin
          out = 8'h11;
        end
        4'hc: begin
          out = 8'h12;
        end
        4'hd: begin
          out = 8'h13;
        end
        4'he: begin
          out = 8'h14;
        end
        4'hf: begin
          out = 8'h15;
        end
        5'h10: begin
          out = 8'h16;
        end
        default: begin
          out = 8'h00;
        end
      endcase
    end
  end
endmodule
