/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [3:0] io_sel,
    output reg [7:0] io_seg,
    input [3:0] p1Raw,
    input [3:0] p2Raw,
    input start,
    output reg [3:0] p1LED,
    output reg [3:0] p2LED
  );
  
  
  
  reg rst;
  
  reg [16:0] instruction;
  
  reg [3:0] p1input;
  
  reg [3:0] p2input;
  
  reg [5:0] p1ideal;
  
  reg [5:0] p2ideal;
  
  reg dynamicRst1;
  
  reg dynamicRst2;
  
  reg startCounterRst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [1-1:0] M_p1d1_out;
  reg [1-1:0] M_p1d1_in;
  debounce_2 p1d1 (
    .clk(clk),
    .in(M_p1d1_in),
    .out(M_p1d1_out)
  );
  wire [1-1:0] M_p1d2_out;
  reg [1-1:0] M_p1d2_in;
  debounce_2 p1d2 (
    .clk(clk),
    .in(M_p1d2_in),
    .out(M_p1d2_out)
  );
  wire [1-1:0] M_p1d3_out;
  reg [1-1:0] M_p1d3_in;
  debounce_2 p1d3 (
    .clk(clk),
    .in(M_p1d3_in),
    .out(M_p1d3_out)
  );
  wire [1-1:0] M_p1d4_out;
  reg [1-1:0] M_p1d4_in;
  debounce_2 p1d4 (
    .clk(clk),
    .in(M_p1d4_in),
    .out(M_p1d4_out)
  );
  wire [1-1:0] M_p2d1_out;
  reg [1-1:0] M_p2d1_in;
  debounce_2 p2d1 (
    .clk(clk),
    .in(M_p2d1_in),
    .out(M_p2d1_out)
  );
  wire [1-1:0] M_p2d2_out;
  reg [1-1:0] M_p2d2_in;
  debounce_2 p2d2 (
    .clk(clk),
    .in(M_p2d2_in),
    .out(M_p2d2_out)
  );
  wire [1-1:0] M_p2d3_out;
  reg [1-1:0] M_p2d3_in;
  debounce_2 p2d3 (
    .clk(clk),
    .in(M_p2d3_in),
    .out(M_p2d3_out)
  );
  wire [1-1:0] M_p2d4_out;
  reg [1-1:0] M_p2d4_in;
  debounce_2 p2d4 (
    .clk(clk),
    .in(M_p2d4_in),
    .out(M_p2d4_out)
  );
  wire [1-1:0] M_startCond_out;
  reg [1-1:0] M_startCond_in;
  button_conditioner_10 startCond (
    .clk(clk),
    .in(M_startCond_in),
    .out(M_startCond_out)
  );
  wire [1-1:0] M_startDetect_out;
  reg [1-1:0] M_startDetect_in;
  edge_detector_11 startDetect (
    .clk(clk),
    .in(M_startDetect_in),
    .out(M_startDetect_out)
  );
  wire [1-1:0] M_counter1_value;
  counter_12 counter1 (
    .clk(clk),
    .rst(dynamicRst1),
    .value(M_counter1_value)
  );
  wire [1-1:0] M_counter2_value;
  counter_12 counter2 (
    .clk(clk),
    .rst(dynamicRst2),
    .value(M_counter2_value)
  );
  wire [2-1:0] M_startCounter_value;
  counter_14 startCounter (
    .clk(clk),
    .rst(startCounterRst),
    .value(M_startCounter_value)
  );
  localparam WAIT_state = 4'd0;
  localparam STARTING_state = 4'd1;
  localparam CHECKZERO_state = 4'd2;
  localparam CHECKZEROI_state = 4'd3;
  localparam CHECKANS_state = 4'd4;
  localparam CHECKANSI_state = 4'd5;
  localparam SCOREMINUS_state = 4'd6;
  localparam SCOREPLUS_state = 4'd7;
  localparam CHECKWIN_state = 4'd8;
  localparam CHECKSCOREZERO_state = 4'd9;
  localparam CHECKWINI_state = 4'd10;
  localparam CHECKSCOREZEROI_state = 4'd11;
  localparam WIN_state = 4'd12;
  
  reg [3:0] M_state_d, M_state_q = WAIT_state;
  localparam P1_player = 1'd0;
  localparam P2_player = 1'd1;
  
  reg M_player_d, M_player_q = P1_player;
  reg M_p1Interim_d, M_p1Interim_q = 1'h0;
  reg M_p2Interim_d, M_p2Interim_q = 1'h0;
  reg M_winSounded_d, M_winSounded_q = 1'h0;
  wire [16-1:0] M_cpu16_out;
  wire [16-1:0] M_cpu16_s1;
  wire [16-1:0] M_cpu16_s2;
  cpu_15 cpu16 (
    .clk(clk),
    .rst(rst),
    .instr(instruction),
    .p1_button(p1input),
    .p2_button(p2input),
    .out(M_cpu16_out),
    .s1(M_cpu16_s1),
    .s2(M_cpu16_s2)
  );
  wire [7-1:0] M_seg_seg;
  wire [4-1:0] M_seg_sel;
  reg [16-1:0] M_seg_values;
  multi_seven_seg_16 seg (
    .clk(clk),
    .rst(rst),
    .values(M_seg_values),
    .seg(M_seg_seg),
    .sel(M_seg_sel)
  );
  wire [64-1:0] M_random_out;
  reg [1-1:0] M_random_next;
  randomSet_17 random (
    .clk(clk),
    .rst(rst),
    .next(M_random_next),
    .out(M_random_out)
  );
  wire [1-1:0] M_tx_tx;
  wire [1-1:0] M_tx_busy;
  reg [8-1:0] M_tx_data;
  reg [1-1:0] M_tx_new_data;
  uart_tx_18 tx (
    .clk(clk),
    .rst(rst),
    .block(1'h0),
    .data(M_tx_data),
    .new_data(M_tx_new_data),
    .tx(M_tx_tx),
    .busy(M_tx_busy)
  );
  
  wire [8-1:0] M_dig2to1P1_out;
  reg [8-1:0] M_dig2to1P1_num;
  dig2to1_19 dig2to1P1 (
    .num(M_dig2to1P1_num),
    .out(M_dig2to1P1_out)
  );
  
  wire [8-1:0] M_dig2to1P2_out;
  reg [8-1:0] M_dig2to1P2_num;
  dig2to1_19 dig2to1P2 (
    .num(M_dig2to1P2_num),
    .out(M_dig2to1P2_out)
  );
  
  always @* begin
    M_state_d = M_state_q;
    M_player_d = M_player_q;
    M_p1Interim_d = M_p1Interim_q;
    M_p2Interim_d = M_p2Interim_q;
    M_winSounded_d = M_winSounded_q;
    
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    p1ideal = M_random_out[(M_cpu16_s1)*4+3-:4];
    p2ideal = M_random_out[(M_cpu16_s2)*4+3-:4];
    p1LED = p1ideal;
    p2LED = p2ideal;
    M_dig2to1P1_num = M_cpu16_s1;
    M_dig2to1P2_num = M_cpu16_s2;
    M_seg_values = {M_dig2to1P1_out, M_dig2to1P2_out};
    io_seg = ~M_seg_seg;
    io_sel = ~M_seg_sel;
    M_p1d1_in = ~p1Raw[0+0-:1];
    M_p1d2_in = ~p1Raw[1+0-:1];
    M_p1d3_in = ~p1Raw[2+0-:1];
    M_p1d4_in = ~p1Raw[3+0-:1];
    p1input = {M_p1d4_out, M_p1d3_out, M_p1d2_out, M_p1d1_out};
    M_p2d1_in = ~p2Raw[0+0-:1];
    M_p2d2_in = ~p2Raw[1+0-:1];
    M_p2d3_in = ~p2Raw[2+0-:1];
    M_p2d4_in = ~p2Raw[3+0-:1];
    p2input = {M_p2d4_out, M_p2d3_out, M_p2d2_out, M_p2d1_out};
    M_startCond_in = ~start;
    M_startDetect_in = M_startCond_out;
    dynamicRst1 = 1'h0;
    dynamicRst2 = 1'h0;
    led = 1'h0;
    instruction = 17'h1ffff;
    M_random_next = 1'h0;
    startCounterRst = 1'h1;
    M_tx_data = 1'h0;
    M_tx_new_data = 1'h0;
    avr_rx = M_tx_tx;
    
    case (M_state_q)
      WAIT_state: begin
        p1LED = 4'hf;
        p2LED = 4'hf;
        led[0+3-:4] = p1input;
        led[4+3-:4] = p2input;
        M_random_next = 1'h1;
        if (M_startDetect_out) begin
          M_state_d = STARTING_state;
        end
      end
      STARTING_state: begin
        startCounterRst = 1'h0;
        p1LED = 1'h0;
        p2LED = 1'h0;
        
        case (M_startCounter_value)
          1'h0: begin
            M_seg_values = 16'h3ccc;
          end
          1'h1: begin
            M_seg_values = 16'h32cc;
          end
          2'h2: begin
            M_seg_values = 16'h321c;
          end
          2'h3: begin
            M_state_d = CHECKZERO_state;
          end
        endcase
      end
      CHECKZERO_state: begin
        
        case (M_player_q)
          P1_player: begin
            instruction = 17'h0c033;
          end
          P2_player: begin
            instruction = 17'h10033;
          end
        endcase
        M_state_d = CHECKZEROI_state;
      end
      CHECKZEROI_state: begin
        
        case (M_player_q)
          P1_player: begin
            if (M_cpu16_out) begin
              M_p1Interim_d = 1'h0;
              dynamicRst1 = 1'h1;
              M_player_d = P2_player;
              M_state_d = CHECKZERO_state;
            end else begin
              if (M_p1Interim_q) begin
                M_state_d = CHECKZERO_state;
                M_player_d = P2_player;
              end else begin
                M_state_d = CHECKANS_state;
              end
            end
          end
          P2_player: begin
            if (M_cpu16_out) begin
              M_p2Interim_d = 1'h0;
              dynamicRst2 = 1'h1;
              M_player_d = P1_player;
              M_state_d = CHECKZERO_state;
            end else begin
              if (M_p2Interim_q) begin
                M_state_d = CHECKZERO_state;
                M_player_d = P1_player;
              end else begin
                M_state_d = CHECKANS_state;
              end
            end
          end
        endcase
      end
      CHECKANS_state: begin
        
        case (M_player_q)
          P1_player: begin
            instruction = {3'h3, 2'h0, p1ideal, 6'h33};
          end
          P2_player: begin
            instruction = {3'h4, 2'h0, p2ideal, 6'h33};
          end
        endcase
        M_state_d = CHECKANSI_state;
      end
      CHECKANSI_state: begin
        
        case (M_player_q)
          P1_player: begin
            if (M_cpu16_out) begin
              M_state_d = SCOREPLUS_state;
            end else begin
              if (M_counter1_value) begin
                M_state_d = CHECKSCOREZERO_state;
              end else begin
                M_player_d = P2_player;
                M_state_d = CHECKZERO_state;
              end
            end
          end
          P2_player: begin
            if (M_cpu16_out) begin
              M_state_d = SCOREPLUS_state;
            end else begin
              if (M_counter2_value) begin
                M_state_d = CHECKSCOREZERO_state;
              end else begin
                M_player_d = P1_player;
                M_state_d = CHECKZERO_state;
              end
            end
          end
        endcase
      end
      SCOREPLUS_state: begin
        
        case (M_player_q)
          P1_player: begin
            instruction = 17'h05040;
            M_p1Interim_d = 1'h1;
            M_state_d = CHECKWIN_state;
            if (!M_tx_busy) begin
              M_tx_data = 7'h61;
              M_tx_new_data = 1'h1;
            end
          end
          P2_player: begin
            instruction = 17'h0a040;
            M_p2Interim_d = 1'h1;
            M_state_d = CHECKWIN_state;
            if (!M_tx_busy) begin
              M_tx_data = 7'h62;
              M_tx_new_data = 1'h1;
            end
          end
        endcase
      end
      CHECKWIN_state: begin
        
        case (M_player_q)
          P1_player: begin
            instruction = 17'h04433;
          end
          P2_player: begin
            instruction = 17'h08433;
          end
        endcase
        M_state_d = CHECKWINI_state;
      end
      CHECKWINI_state: begin
        
        case (M_player_q)
          P1_player: begin
            if (M_cpu16_out) begin
              M_state_d = WIN_state;
            end else begin
              M_player_d = P2_player;
              M_state_d = CHECKZERO_state;
            end
          end
          P2_player: begin
            if (M_cpu16_out) begin
              M_state_d = WIN_state;
            end else begin
              M_player_d = P1_player;
              M_state_d = CHECKZERO_state;
            end
          end
        endcase
      end
      WIN_state: begin
        
        case (M_player_q)
          P1_player: begin
            p1LED = {3'h4{M_counter1_value}};
            p2LED = 1'h0;
            if (!M_tx_busy & !M_winSounded_q) begin
              M_tx_data = 7'h65;
              M_tx_new_data = 1'h1;
              M_winSounded_d = 1'h1;
            end
          end
          P2_player: begin
            p2LED = {3'h4{M_counter1_value}};
            p1LED = 1'h0;
            if (!M_tx_busy & !M_winSounded_q) begin
              M_tx_data = 7'h66;
              M_tx_new_data = 1'h1;
              M_winSounded_d = 1'h1;
            end
          end
        endcase
        if (M_startDetect_out) begin
          rst = 1'h1;
        end
      end
      CHECKSCOREZERO_state: begin
        
        case (M_player_q)
          P1_player: begin
            instruction = 17'h04033;
            M_state_d = CHECKSCOREZEROI_state;
          end
          P2_player: begin
            instruction = 17'h08033;
            M_state_d = CHECKSCOREZEROI_state;
          end
        endcase
      end
      CHECKSCOREZEROI_state: begin
        
        case (M_player_q)
          P1_player: begin
            if (M_cpu16_out) begin
              M_player_d = P2_player;
              M_state_d = CHECKZERO_state;
            end else begin
              M_state_d = SCOREMINUS_state;
            end
          end
          P2_player: begin
            if (M_cpu16_out) begin
              M_player_d = P1_player;
              M_state_d = CHECKZERO_state;
            end else begin
              M_state_d = SCOREMINUS_state;
            end
          end
        endcase
      end
      SCOREMINUS_state: begin
        
        case (M_player_q)
          P1_player: begin
            instruction = 17'h05041;
            M_p1Interim_d = 1'h1;
            M_state_d = CHECKZERO_state;
            M_player_d = P2_player;
            if (!M_tx_busy) begin
              M_tx_data = 7'h63;
              M_tx_new_data = 1'h1;
            end
          end
          P2_player: begin
            instruction = 17'h0a041;
            M_p2Interim_d = 1'h1;
            M_state_d = CHECKZERO_state;
            M_player_d = P1_player;
            if (!M_tx_busy) begin
              M_tx_data = 7'h64;
              M_tx_new_data = 1'h1;
            end
          end
        endcase
      end
    endcase
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_p1Interim_q <= 1'h0;
      M_p2Interim_q <= 1'h0;
      M_winSounded_q <= 1'h0;
      M_state_q <= 1'h0;
      M_player_q <= 1'h0;
    end else begin
      M_p1Interim_q <= M_p1Interim_d;
      M_p2Interim_q <= M_p2Interim_d;
      M_winSounded_q <= M_winSounded_d;
      M_state_q <= M_state_d;
      M_player_q <= M_player_d;
    end
  end
  
endmodule
