/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     WIDTH = WIDTH
*/
module mux8_34 (
    input [15:0] lll,
    input [15:0] llh,
    input [15:0] lhl,
    input [15:0] lhh,
    input [15:0] hll,
    input [15:0] hlh,
    input [15:0] hhl,
    input [15:0] hhh,
    input [2:0] select,
    output reg [15:0] out
  );
  
  localparam WIDTH = 5'h10;
  
  
  always @* begin
    if (!select[2+0-:1] & !select[1+0-:1] & !select[0+0-:1]) begin
      out = lll;
    end else begin
      if (!select[2+0-:1] & !select[1+0-:1] & select[0+0-:1]) begin
        out = llh;
      end else begin
        if (!select[2+0-:1] & select[1+0-:1] & !select[0+0-:1]) begin
          out = lhl;
        end else begin
          if (!select[2+0-:1] & select[1+0-:1] & select[0+0-:1]) begin
            out = lhh;
          end else begin
            if (select[2+0-:1] & !select[1+0-:1] & !select[0+0-:1]) begin
              out = hll;
            end else begin
              if (select[2+0-:1] & !select[1+0-:1] & select[0+0-:1]) begin
                out = hlh;
              end else begin
                if (select[2+0-:1] & select[1+0-:1] & !select[0+0-:1]) begin
                  out = hhl;
                end else begin
                  out = hhh;
                end
              end
            end
          end
        end
      end
    end
  end
endmodule
