/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alutester_8 (
    input clk,
    input rst,
    input [15:0] result,
    input [1:0] testSet,
    output reg [15:0] a,
    output reg [15:0] b,
    output reg [5:0] alufn,
    output reg err,
    output reg complete,
    output reg [5:0] caseNum
  );
  
  
  
  localparam TOTAL_CASES = 5'h1c;
  
  reg [447:0] aArray;
  
  reg [447:0] bArray;
  
  reg [167:0] fnArray;
  
  reg [447:0] idealArray;
  
  wire [5-1:0] M_testCounter_value;
  counter_13 testCounter (
    .clk(clk),
    .rst(rst),
    .value(M_testCounter_value)
  );
  
  always @* begin
    aArray = 448'hf001551055115511fff0c0000030005505c000dd00dd004f0fff51089721b19a19bc2d6ac966172fd64258ff655780009ab8b817263739a7;
    bArray = 448'haa11ffaaffffaaaaaaaa00030003004405c0004d00dd035c004cbe942cade2b4eb4419bcb0bb7c4fbd13024896930008000f000a00070003;
    fnArray = 168'h5d959e6020b7df3cf5d410410410000000218a3860;
    idealArray = 448'h5ffe5545aaeeffbbaaa04000009000000001000000010001000092746a74cee62e7813ae7a21937e93555b47fbea00800000ffee004ccd38;
    if (testSet == 1'h1) begin
      aArray = 448'hf001551055115511fff0c0000030005505c000dd00dd004f0fff51089721b19a19bc2d6ac966172fd64258ff655780009ab8b817263739a7;
      bArray = 448'haa11ffaaffffaaaaaaaa00030003004405c0004d00dd035c004cbe942cade2b4eb4419bcb0bb7c4fbd13024896930008000f000a00070003;
      fnArray = 168'h5d959e6020b7df3cf5d41041041000000021fe3860;
      idealArray = 448'h5ffe5545aaeeffbbaaa04000009000000001000000010001000092746a74cee62e7813ae7a21937e93555b47fbea00800000ffee004ccd38;
    end else begin
      if (testSet == 2'h2) begin
        aArray = 448'hf001551055115511fff0c0000030005505c000dd00dd004f0fff51089721b19a19bc2d6ac966172fd64258ff655780009ab8b817263739a7;
        bArray = 448'haa11ffaaffffaaaaaaaa00030003004405c0004d00dd035c004cbe942cade2b4eb4419bcb0bb7c4fbd13024896930008000f000a00070003;
        fnArray = 168'h5d959e6020b7df3cf5d410410410000000218a3860;
        idealArray = 448'h5ffe5545aaeeffbbaaa04000009000000001000000010001000092746a74cee62e7813ae7a21937e93555b47fbea00800000ffee104ccd38;
      end
    end
    caseNum = M_testCounter_value;
    if (M_testCounter_value == 5'h1c) begin
      a = 1'h0;
      b = 1'h0;
      alufn = 1'h0;
      err = 1'h0;
      complete = 1'h1;
    end else begin
      a = aArray[(M_testCounter_value)*16+15-:16];
      b = bArray[(M_testCounter_value)*16+15-:16];
      alufn = fnArray[(M_testCounter_value)*6+5-:6];
      complete = 1'h0;
      err = result != idealArray[(M_testCounter_value)*16+15-:16];
    end
  end
endmodule
