/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    output reg [23:0] io_led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  reg [15:0] aluResult;
  
  reg [1:0] testSet;
  
  integer currentResult;
  
  integer currentAlufn;
  
  integer currentCase;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [1-1:0] M_center_cond_out;
  reg [1-1:0] M_center_cond_in;
  button_conditioner_2 center_cond (
    .clk(clk),
    .in(M_center_cond_in),
    .out(M_center_cond_out)
  );
  wire [1-1:0] M_center_detect_out;
  reg [1-1:0] M_center_detect_in;
  edge_detector_3 center_detect (
    .clk(clk),
    .in(M_center_detect_in),
    .out(M_center_detect_out)
  );
  wire [1-1:0] M_left_cond_out;
  reg [1-1:0] M_left_cond_in;
  button_conditioner_2 left_cond (
    .clk(clk),
    .in(M_left_cond_in),
    .out(M_left_cond_out)
  );
  wire [1-1:0] M_left_detect_out;
  reg [1-1:0] M_left_detect_in;
  edge_detector_3 left_detect (
    .clk(clk),
    .in(M_left_detect_in),
    .out(M_left_detect_out)
  );
  wire [1-1:0] M_right_cond_out;
  reg [1-1:0] M_right_cond_in;
  button_conditioner_2 right_cond (
    .clk(clk),
    .in(M_right_cond_in),
    .out(M_right_cond_out)
  );
  wire [1-1:0] M_right_detect_out;
  reg [1-1:0] M_right_detect_in;
  edge_detector_3 right_detect (
    .clk(clk),
    .in(M_right_detect_in),
    .out(M_right_detect_out)
  );
  wire [1-1:0] M_up_cond_out;
  reg [1-1:0] M_up_cond_in;
  button_conditioner_2 up_cond (
    .clk(clk),
    .in(M_up_cond_in),
    .out(M_up_cond_out)
  );
  wire [1-1:0] M_up_detect_out;
  reg [1-1:0] M_up_detect_in;
  edge_detector_3 up_detect (
    .clk(clk),
    .in(M_up_detect_in),
    .out(M_up_detect_out)
  );
  wire [16-1:0] M_tester_a;
  wire [16-1:0] M_tester_b;
  wire [6-1:0] M_tester_alufn;
  wire [1-1:0] M_tester_err;
  wire [1-1:0] M_tester_complete;
  wire [6-1:0] M_tester_caseNum;
  alutester_10 tester (
    .clk(clk),
    .rst(M_center_detect_out | M_left_detect_out | M_right_detect_out),
    .result(aluResult),
    .testSet(testSet),
    .a(M_tester_a),
    .b(M_tester_b),
    .alufn(M_tester_alufn),
    .err(M_tester_err),
    .complete(M_tester_complete),
    .caseNum(M_tester_caseNum)
  );
  localparam WAITA_state = 3'd0;
  localparam WAITB_state = 3'd1;
  localparam MRESULT_state = 3'd2;
  localparam TESTING_state = 3'd3;
  localparam FNERROR_state = 3'd4;
  localparam VALERROR_state = 3'd5;
  
  reg [2:0] M_state_d, M_state_q = WAITA_state;
  localparam PASS_testState = 2'd0;
  localparam FNFAIL_testState = 2'd1;
  localparam VALFAIL_testState = 2'd2;
  
  reg [1:0] M_testState_d, M_testState_q = PASS_testState;
  reg [15:0] M_manualA_d, M_manualA_q = 1'h0;
  reg [15:0] M_manualB_d, M_manualB_q = 1'h0;
  reg [5:0] M_manualAlufn_d, M_manualAlufn_q = 1'h0;
  
  wire [16-1:0] M_alu16_result;
  wire [1-1:0] M_alu16_z;
  wire [1-1:0] M_alu16_v;
  wire [1-1:0] M_alu16_n;
  wire [1-1:0] M_alu16_err;
  alu_11 alu16 (
    .a(M_tester_a),
    .b(M_tester_b),
    .alufn(M_tester_alufn),
    .result(M_alu16_result),
    .z(M_alu16_z),
    .v(M_alu16_v),
    .n(M_alu16_n),
    .err(M_alu16_err)
  );
  
  wire [16-1:0] M_malu16_result;
  wire [1-1:0] M_malu16_z;
  wire [1-1:0] M_malu16_v;
  wire [1-1:0] M_malu16_n;
  wire [1-1:0] M_malu16_err;
  alu_11 malu16 (
    .a(M_manualA_q),
    .b(M_manualB_q),
    .alufn(M_manualAlufn_q),
    .result(M_malu16_result),
    .z(M_malu16_z),
    .v(M_malu16_v),
    .n(M_malu16_n),
    .err(M_malu16_err)
  );
  
  always @* begin
    M_testState_d = M_testState_q;
    M_state_d = M_state_q;
    M_manualA_d = M_manualA_q;
    M_manualB_d = M_manualB_q;
    M_manualAlufn_d = M_manualAlufn_q;
    
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    M_center_cond_in = io_button[1+0-:1];
    M_center_detect_in = M_center_cond_out;
    M_left_cond_in = io_button[3+0-:1];
    M_left_detect_in = M_left_cond_out;
    M_right_cond_in = io_button[4+0-:1];
    M_right_detect_in = M_right_cond_out;
    M_up_cond_in = io_button[0+0-:1];
    M_up_detect_in = M_up_cond_out;
    io_led = 24'h000000;
    
    case (M_state_q)
      WAITA_state: begin
        io_led = io_dip;
        if (M_center_detect_out) begin
          M_testState_d = PASS_testState;
          M_state_d = TESTING_state;
        end else begin
          if (M_right_detect_out) begin
            M_testState_d = FNFAIL_testState;
            M_state_d = TESTING_state;
          end else begin
            if (M_left_detect_out) begin
              M_testState_d = VALFAIL_testState;
              M_state_d = TESTING_state;
            end else begin
              if (M_up_detect_out) begin
                M_state_d = WAITB_state;
                M_manualA_d = io_dip[0+15-:16];
              end
            end
          end
        end
      end
      WAITB_state: begin
        io_led = io_dip;
        M_manualB_d = io_dip[0+15-:16];
        M_manualAlufn_d = io_dip[16+5-:6];
        if (M_up_detect_out) begin
          M_state_d = MRESULT_state;
        end
      end
      MRESULT_state: begin
        io_led[16+5-:6] = M_manualAlufn_q;
        io_led[0+15-:16] = M_malu16_result;
        if (M_malu16_err) begin
          io_led[23+0-:1] = 1'h1;
        end
        if (M_up_detect_out) begin
          M_state_d = WAITA_state;
        end
      end
      TESTING_state: begin
        aluResult = M_alu16_result;
        currentResult = M_alu16_result;
        currentAlufn = M_tester_alufn;
        currentCase = M_tester_caseNum;
        
        case (M_testState_q)
          PASS_testState: begin
            testSet = 2'h0;
          end
          FNFAIL_testState: begin
            testSet = 2'h1;
          end
          VALFAIL_testState: begin
            testSet = 2'h2;
          end
        endcase
        io_led[0+15-:16] = aluResult;
        io_led[16+5-:6] = M_tester_caseNum;
        if (M_center_detect_out | M_tester_complete) begin
          M_state_d = WAITA_state;
        end
        if (M_alu16_err) begin
          M_state_d = FNERROR_state;
        end else begin
          if (M_tester_err) begin
            M_state_d = VALERROR_state;
          end
        end
      end
      FNERROR_state: begin
        io_led[22+0-:1] = 1'h1;
        io_led[16+5-:6] = currentCase;
        io_led[0+5-:6] = currentAlufn;
        if (M_center_detect_out) begin
          M_state_d = WAITA_state;
        end
      end
      VALERROR_state: begin
        io_led[23+0-:1] = 1'h1;
        io_led[0+15-:16] = currentResult;
        io_led[16+5-:6] = currentCase;
        if (M_center_detect_out) begin
          M_state_d = WAITA_state;
        end
      end
    endcase
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
  end
  
  always @(posedge clk) begin
    M_manualA_q <= M_manualA_d;
    M_manualB_q <= M_manualB_d;
    M_manualAlufn_q <= M_manualAlufn_d;
    M_state_q <= M_state_d;
    M_testState_q <= M_testState_d;
  end
  
endmodule
